[profile.default]

# project
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./deploy"}]

broadcast = 'broadcast/default'
cache_path = 'cache/default'
test = 'test'

# compiler
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 200
extra_output_files = [
    'abi',
]

# test
no_match_path = "./test/forked/**"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
local-mainnet = "http://localhost:8545"


[profile.mainnet-production]
# FOUNDRY_PROFILE=mainnet-production
# inherits from default profile

# project
cache_path = 'cache/mainnet-production'
broadcast = 'broadcast/mainnet-production'
test = 'no-test'

# compiler
optimizer_runs = 99999
libraries = [
    'script/helper/ArraysHelper.sol:ArraysHelper:0x7dF191D01252D2C0BABf77c725c63D69fe6EAA1a',
    'src/libraries/ArrayMapping.sol:ArrayMappingUint256:0xB6B08a9ed9282c695ddFbfA81d9ebF208b4c1De0',
    'src/libraries/ReallocationLib.sol:ReallocationLib:0x49CE6640EB2D89F80395C1a3695cc3a01b5C7bc1',
    'src/libraries/SpoolUtils.sol:SpoolUtils:0xCB3fECd1D5eabB1b18383604A28352c17Bdfef89',
    'src/strategies/libraries/EthFrxEthAssetGroupAdapter.sol:EthFrxEthAssetGroupAdapter:0xE23681bAA697EF5054E2D8C397ae59145027625D',
    'src/strategies/libraries/EthStEthAssetGroupAdapter.sol:EthStEthAssetGroupAdapter:0x1516eb3a54377168b6b184326200f4258C3529dF'
]

[profile.sepolia-production]
# FOUNDRY_PROFILE=sepolia-production
# inherits from default profile

# project
cache_path = 'cache/sepolia-production'
broadcast = 'broadcast/sepolia-production'
test = 'no-test'

# compiler
optimizer_runs = 99999
libraries = [
    "script/helper/ArraysHelper.sol:ArraysHelper:",
    "src/libraries/ArrayMapping.sol:ArrayMappingUint256:0xa59995f217d8c8ecfe3cd80ac00cdae33e2deeff",
    "src/libraries/ReallocationLib.sol:ReallocationLib:0x3ffda89a5f87d99de88bc0617d95c7e5dde0408f",
    "src/libraries/SpoolUtils.sol:SpoolUtils:0x5049d7d26ab755ca8489ccc30d19e92856e9be72"
]

[profile.arbitrum-production]
# FOUNDRY_PROFILE=arbitrum-production
# inherits from default profile

# project
cache_path = 'cache/arbitrum-production'
broadcast = 'broadcast/arbitrum-production'
test = 'no-test'

# compiler
optimizer_runs = 99999
libraries = [
    "script/helper/ArraysHelper.sol:ArraysHelper:0x1cc307ce564a41a1823f7c6e319b75c139747a32",
    "src/libraries/ArrayMapping.sol:ArrayMappingUint256:0x8d4fe5840fead29f30d5fb9f3ba6fdb6640de8ba",
    "src/libraries/ReallocationLib.sol:ReallocationLib:0xc6f00a9d10263941998d7fd4e4758f1497babdd6",
    "src/libraries/SpoolUtils.sol:SpoolUtils:0x9a6a0820738f6f18f39f9e7109fea44de85bd468",
    "src/strategies/arbitrum/libraries/GammaCamelotPriceHelper.sol:GammaCamelotPriceHelper:0x1847118d72d1c48c37c5927f7fe89a79bcce5b5f"
]
