[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# optimizer
optimizer = true
optimizer_runs = 200

# test
no_match_path = "./test/forked/**"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
