name: test


on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

  workflow_dispatch:
  
env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build and coverage
        run: |
          forge --version
          forge build --sizes > sizes_output.txt
          forge coverage > coverage_output.txt

        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
          forge test --json > test_output.txt
        id: test

  OUTPUT:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install ts-node
        run: |
          npm i ts-node -g
          npm i --save-dev @types/node

      - name: generate output
        run: ts-node ./outputparser.ts
