name: test


on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-60ec00296f00754bc21ed68fd05ab6b54b50e024

      - name: Run Forge fmt check
        run: |
          forge --version
          forge fmt --check
        id: fmt_check

      - name: Run Forge build
        run: |
          forge build --skip script --skip test --sizes
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge t -vvv
        id: test

      - name: Run Forge coverage
        run: |
          forge coverage

        id: coverage